# Configuración de Netlify para MAPO Frontend

[build]
  # Directorio donde está el código fuente
  base = "."
  
  # Comando para construir la aplicación
  command = "npm run build"
  
  # Directorio donde se genera el build
  publish = "build"

# Variables de entorno para el build
[build.environment]
  REACT_APP_API_BASE_URL = "http://142.93.187.32:8000"
  REACT_APP_ENVIRONMENT = "production"
  # Optimización para React
  GENERATE_SOURCEMAP = "false"
  CI = "false"

# Headers para mejorar seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Cache para archivos estáticos
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración para manejar CORS si es necesario
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirect rules (también se puede usar _redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["us"]}

# Configuración de funciones (si las necesitas más adelante)
[functions]
  directory = "netlify/functions"