[build]
  ## Proxy para evitar Mixed Content (HTTP to HTTPS)
# Redirige las peticiones /api/* al backend HTTP
# Ejemplo: /api/categories -> http://https://142.93.187.32.nip.io/categories
[[redirects]]
  from = "/api/*"
  to = "http://https://142.93.187.32.nip.io/:splat"
  status = 200
  force = true

# Configuración para Single Page Application (SPA)
# Redirige todas las rutas al index.html para que React Router funcione
# NOTA: Debe ir después del proxy de API
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = falsed que ignora conflictos de peer dependencies
  command = "npm run build"
  
  # Directorio donde se generan los archivos del build
  publish = "build"

# Configurar npm para usar --legacy-peer-deps en todas las instalaciones
[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

# Proxy para evitar Mixed Content (HTTP to HTTPS)
# Redirige las peticiones /api/* al backend HTTP
# :splat captura todo después de /api/ y lo reenvía al backend
[[redirects]]
  from = "/api/*"
  to = "http://https://142.93.187.32.nip.io/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Configuración para Single Page Application (SPA)
# Redirige todas las rutas al index.html para que React Router funcione
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
