[build]
  # Comando de build que ignora conflictos de peer dependencies
  command = "npm run build"
  
  # Directorio donde se generan los archivos del build
  publish = "build"

# Configurar npm para usar --legacy-peer-deps en todas las instalaciones
[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

# Proxy para evitar Mixed Content (HTTP to HTTPS)
# Redirige las peticiones /api/* al backend HTTP
# IMPORTANTE: Este redirect debe ir ANTES del redirect del SPA
[[redirects]]
  from = "/api/*"
  to = "http://142.93.187.32:8000/:splat"
  status = 200
  force = true

# Configuración para Single Page Application (SPA)
# Redirige todas las rutas al index.html para que React Router funcione
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
